version: '3.8'
services:
    php-apache-environment:
        container_name: vsnippet-sosqli-33
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./src:/var/www/html/
        ports:
            - 1337:80
    db:
        container_name: vsnippet-mysql-db
        volumes:
            - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
        image: mysql
        restart: always
        environment:
            MYSQL_DATABASE: ywhvsnippet
            MYSQL_USER: vsnippet
            MYSQL_PASSWORD: vsnippet
            MYSQL_ROOT_PASSWORD: supervulnerableroot
        ports:
            - "1338:3306"
